### ISSUE TITLE
@Document uri scope in queries

### ISSUE THREAD

**Issue by malteseduck** [malteseduck/spring-data-marklogic#44]
If you specify the uri value to anything other than the default "/" the `wrapQuery()` should use that to scope queries so only entities under the specified uri are returned.

**Comment by saleco** [comment]
Hello! 
I'm using uri in @Document on my entity but it still not using it as a filter on the query as follows:
`<search xmlns=\"http://marklogic.com/appservices/search\"><query xmlns=\"http://marklogic.com/appservices/search\" xmlns:search=\"http://marklogic.com/appservices/search\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><value-query type=\"string\"><json-property>standardCode</json-property><text>PP01</text><term-option>exact</term-option><weight>1.0</weight></value-query></query></search>`

I see this bug fix is not released yet right? Do you have a due date for the release?
